spring.mvc.view.suffix=.html

# PostgreSQL datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/futureinterior
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mvc.format.date=dd/MM/yyyy
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.continue-on-error=true

logging.level.root=warn

spring.servlet.multipart.max-file-size=20MB 
spring.servlet.multipart.max-request-size=20MB

# --------  MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thinhnlppc04695@fpt.edu.vn
spring.mail.password=dquevevsuhtmsbos
spring.mail.properties.mail.smpt.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true